### ISSUE TITLE
EPIC: Benetech Challenge

### ISSUE THREAD

**Issue by shindesimantini6** [shindesimantini6/Bene-Tahini#7]
Convert charts into data series. 

Next TO DO to finish the goal: 

- [ ] EDA (https://github.com/shindesimantini6/Bene-Tahini/issues/2)
- [ ] Step 1: Train a baseline CNN (https://github.com/shindesimantini6/Bene-Tahini/issues/3)
- [ ] Step 2: Add annotations and custom markers (https://github.com/shindesimantini6/Bene-Tahini/issues/4)
- [ ] Step 3: Train Object Detection Neural Network and predict bounding boxes. (https://github.com/shindesimantini6/Bene-Tahini/issues/5)
- [ ] Step 4: Get Text and numbers from OCR (https://github.com/shindesimantini6/Bene-Tahini/issues/6)

\rfc @Kestener @molemae @Nazila-H @GerritKu

**Comment by shindesimantini6** [comment]
@Kestener @Nazila-H @molemae Please assign yourself to a task from the first three. We can try finishing these this week and continue with the rest over the next week. 

Let me know if you wanna do the tasks some other way.
